# Automatically created bt "no-headache-django" project.
# Star me on github http://github.com/mrsaemir/no-headache-django

version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
    volumes:
      - ./:/home/user/project_core
      - ../development_data/static:/home/user/static/
      - ../development_data/media:/home/user/media/

    command: bash -c "python manage.py runserver 0.0.0.0:8000"

    env_file:
      - vars.env


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../development_data/postgres:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django_password