# Automatically created bt "no-headache-django" project.
# Star me on github http://github.com/mrsaemir/no-headache-django

version: '3'

services:
  website:
    restart: always
    build: .
    ports:
      - 8000:8000
    networks:
      project_network:
    depends_on:
      - db
    volumes:
      - ./:/home/user/project_core
      - ../development_data/static:/home/user/static/
      - ../development_data/media:/home/user/media/

    command: bash -c "python manage.py runserver 0.0.0.0:8000"

    env_file:
      - vars.env

  db:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=some_password
      - MONGO_INITDB_DATABASE=some_db
    networks:
      project_network:
    volumes:
      - ../development_data/mongodb:/data/db

  mongo-express:
    restart: always
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=some_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=some_password
    networks:
      project_network:

    depends_on:
      - db


networks:
  project_network:
